### PR TITLE
fix: use 3.1.0 so swagger-codegen works and add an instruction to the README

### PR DESCRIPTION
**Pull request by rb455**
This change allows generating the self-contained OpenAPI specification file by fixing the OpenAPI version.

Ticket Link: discussion started in this thread https://immersve.slack.com/archives/C06BAC49Y81/p1714952775052809

### CODE REVIEW

**Comment by ncjones** [comment]
@rb455 looks good. How do you install `swagger-codegen` though?

**Comment by rb455** [comment]
> @rb455 looks good. How do you install `swagger-codegen` though?

I installed it using `brew install swagger-codegen` (https://github.com/swagger-api/swagger-codegen?tab=readme-ov-file#homebrew) but I figured it would be inconsiderate to put that in the instruction, since some might want to build from source/use another OS

**Comment by rb455** [comment]
@ncjones please review again

**Review by NicBathgate — APPROVED** [review]
@rb455 nice!

**Pull request merged**
