### PR TITLE
add partner statement address updates

### PR DESCRIPTION
**Pull request by forktrucka**
Updates the documentation around address claims.

Fixes up the example for `GET Partner statements` to show a valid example.

Ticket Link: https://www.notion.so/immersve/Update-references-and-guides-be1cff22e93945dcb0c6bbb31b645039?pvs=4

### CODE REVIEW

**Comment by forktrucka** [comment]
https://364-merge--jovial-scone-ec740d.netlify.app

**Review by rb455 — APPROVED** [review]

**Comment by forktrucka** [comment]
Won't be merging this until the functionality is complete.

**Review by NicBathgate — APPROVED** [review]
Nice one team!

**Review by NicBathgate — APPROVED** [review]
Awesome, example looking great now 😻

**Pull request merged**
